config/routes.rb
Rails.application.routes.draw do
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  devise_for :users
  get 'home/index'
  root 'home#index'
  match 'auth/:provider/callback', to: 'sessions#create',via: [:get, :post]
  match 'auth/failure', to: redirect('/'),via: [:get, :post]
  match 'signout', to: 'sessions#destroy', as: 'signout',via: [:get, :post]

	resources :univercities do 
	  resources :colleges,:only => [:show]
	end

  resources :batches, :only => [:show, :index] do
    resources :courses,:sections, :only => [:show] do 
      resources :time_table, :only => [:show]
    end
  end
  
end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
    if user.has_role? :Admin
      can :manage, Company
    else
      can :read, :all
    end 
  end
end

app/models/batch.rb
class Batch < ActiveRecord::Base
	has_many :courses
	has_many :sections
	has_many :time_table
end

app/models/college.rb
class College < ActiveRecord::Base
	extend FriendlyId

	resourcify
  belongs_to :univercity

  friendly_id :name, use: :slugged


end

app/models/company.rb
class Company < ActiveRecord::Base
	resourcify
end

app/models/course.rb
class Course < ActiveRecord::Base
  belongs_to :batch
  has_many :subjects
  has_many :time_table
end

app/models/faculty.rb
class Faculty < ActiveRecord::Base
	has_many :subjects
end

app/models/role.rb
class Role < ActiveRecord::Base
  has_and_belongs_to_many :users, :join_table => :users_roles
  belongs_to :resource, :polymorphic => true

  validates :resource_type,
            :inclusion => { :in => Rolify.resource_types },
            :allow_nil => true

  scopify
end

app/models/section.rb
class Section < ActiveRecord::Base
  belongs_to :batch
  has_one :time_table
end

app/models/subject.rb
class Subject < ActiveRecord::Base
  belongs_to :course
  belongs_to :faculty
end

app/models/time_table.rb
class TimeTable < ActiveRecord::Base
  belongs_to :section
  belongs_to :course
  belongs_to :batch
end

app/models/univercity.rb
class Univercity < ActiveRecord::Base
	extend FriendlyId
	
	resourcify
	has_many :colleges

	friendly_id :name, use: :slugged

end

app/models/user.rb
class User < ActiveRecord::Base
  
  rolify
  
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  devise :confirmable

  mount_uploader :image, ImageUploader

  def self.from_omniauth(auth)
	  where(provider: auth.provider, uid: auth.uid).first_or_initialize.tap do |user|
	  	user.email = auth.info.email
	    user.provider = auth.provider
	    user.uid = auth.uid
	    user.name = auth.info.name
	    user.oauth_token = auth.credentials.token
	    user.oauth_expires_at = Time.at(auth.credentials.expires_at)
	    user.save!
	  end
	end


end

app/controllers/batches_controller.rb
class BatchesController < ApplicationController

	def index
		@batches = Batch.all
	end

	def show
		@batch = Batch.find(params[:id])
	end

end

app/controllers/colleges_controller.rb
class CollegesController < ApplicationController
  
  def show
    @univercity = Univercity.friendly.find(params[:univercity_id])
    @college = @univercity.colleges.friendly.find(params[:id])
  end

end

app/controllers/courses_controller.rb
class CoursesController < ApplicationController
	
	def show
		@batch = Batch.find(params[:batch_id])
		@course = @batch.courses.find(params[:id])
	end

end

app/controllers/home_controller.rb
class HomeController < ApplicationController
	def index
	end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
end

app/helpers/application_helper.rb
module ApplicationHelper

	

end

app/helpers/colleges_helper.rb
module CollegesHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/helpers/univercities_helper.rb
module UnivercitiesHelper
def get_colleges(univercity)
	college = univercity.colleges.map(&:name).uniq
end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/batches/index.html.erb
<%- model_class = Batch -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.pluralize.titleize %></h1>
</div>
<table class="table table-striped">
  <thead>
    <tr>
      <th><%= model_class.human_attribute_name(:name) %></th>
      <th><%= model_class.human_attribute_name(:year) %></th>
    </tr>
  </thead>
  <tbody>
    <% @batches.each do |batch| %>
      <tr>
        <td><%= link_to batch.name, batch_path(batch) %></td>
        <td><%= batch.year %></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/batches/show.html.erb
<%- model_class = Batch -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.titleize %></h1>
</div>
<div class="col-md-12">

  <div class="col-md-6">

    <dl class="dl-horizontal">
      <dt><strong><%= model_class.human_attribute_name(:name) %>:</strong></dt>
      <dd><%= link_to @batch.name, batches_path,:class => 'btn btn-info' %></dd>
      <dt><strong><%= model_class.human_attribute_name(:year) %>:</strong></dt>
      <dd><%= @batch.year %></dd>
    </dl>
  
    <dl class="dl-horizontal">
      <dt><strong>Courses in this batch:</strong></dt>
      <dd>
        <% @batch.courses.each do |c|%>
          <%= link_to c.name, batch_course_path(@batch,c),:class => 'btn btn-info'%><br><br>
        <% end %>
      </dd>
    </dl>
  
    <dl class="dl-horizontal">
      <dt><strong>Sections in this batch:</strong></dt>
      <dd>
        <% @batch.sections.each do |c|%>
          <%= link_to c.name, batch_section_path(@batch,c), :class => 'btn btn-info'%><br><br>
        <% end %>
      </dd>
    </dl>

    <%= link_to t('.back', :default => t("helpers.links.back")),
                batches_path, :class => 'btn btn-warning'  %>
  
  </div>
   
</div>