config/routes.rb
Rails.application.routes.draw do
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  devise_for :users
  get 'home/index'
  root 'home#index'
  match 'auth/:provider/callback', to: 'sessions#create',via: [:get, :post]
  match 'auth/failure', to: redirect('/'),via: [:get, :post]
  match 'signout', to: 'sessions#destroy', as: 'signout',via: [:get, :post]

	resources :univercities do 
	  resources :colleges,:only => [:show]
	end

  resources :batches, :only => [:show, :index] do
    resources :courses,:sections, :only => [:show] do 
      resources :time_table, :only => [:show]
    end
  end
  
end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
    if user.has_role? :Admin
      can :manage, Company
    else
      can :read, :all
    end 
  end
end

app/models/batch.rb
class Batch < ActiveRecord::Base
	has_many :courses
	has_many :sections
	has_many :time_table
end

app/models/college.rb
class College < ActiveRecord::Base
	extend FriendlyId

	resourcify
  belongs_to :univercity

  friendly_id :name, use: :slugged


end

app/models/company.rb
class Company < ActiveRecord::Base
	resourcify
end

app/models/course.rb
class Course < ActiveRecord::Base
  belongs_to :batch
  has_many :subjects
  has_many :time_table
end

app/models/faculty.rb
class Faculty < ActiveRecord::Base
	has_many :subjects
end

app/models/role.rb
class Role < ActiveRecord::Base
  has_and_belongs_to_many :users, :join_table => :users_roles
  belongs_to :resource, :polymorphic => true

  validates :resource_type,
            :inclusion => { :in => Rolify.resource_types },
            :allow_nil => true

  scopify
end

app/models/section.rb
class Section < ActiveRecord::Base
  belongs_to :batch
  has_one :time_table
end

app/models/subject.rb
class Subject < ActiveRecord::Base
  belongs_to :course
  belongs_to :faculty
end

app/models/time_table.rb
class TimeTable < ActiveRecord::Base
  belongs_to :section
  belongs_to :course
  belongs_to :batch
end

app/models/univercity.rb
class Univercity < ActiveRecord::Base
	extend FriendlyId
	
	resourcify
	has_many :colleges

	friendly_id :name, use: :slugged

end

app/models/user.rb
class User < ActiveRecord::Base
  
  rolify
  
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  devise :confirmable

  mount_uploader :image, ImageUploader

  def self.from_omniauth(auth)
	  where(provider: auth.provider, uid: auth.uid).first_or_initialize.tap do |user|
	  	user.email = auth.info.email
	    user.provider = auth.provider
	    user.uid = auth.uid
	    user.name = auth.info.name
	    user.oauth_token = auth.credentials.token
	    user.oauth_expires_at = Time.at(auth.credentials.expires_at)
	    user.save!
	  end
	end


end

app/controllers/batches_controller.rb
class BatchesController < ApplicationController

	def index
		@batches = Batch.all
	end

	def show
		@batch = Batch.find(params[:id])
	end

end

app/controllers/colleges_controller.rb
class CollegesController < ApplicationController
  
  def show
    @univercity = Univercity.friendly.find(params[:univercity_id])
    @college = @univercity.colleges.friendly.find(params[:id])
  end

end

app/controllers/courses_controller.rb
class CoursesController < ApplicationController
	
	def show
		@batch = Batch.find(params[:batch_id])
		@course = @batch.courses.find(params[:id])
	end

end

app/controllers/home_controller.rb
class HomeController < ApplicationController
	def index
	end
end

app/controllers/univercities_controller.rb
class UnivercitiesController < ApplicationController
	
	def index
		@univercities = Univercity.all
	end

	def new
		@univercity = Univercity.new
	end

	def edit
		@univercity = Univercity.find(params[:id])
	end

	def show
		@univercity = Univercity.friendly.find(params[:id])
	end

	def create
		@univercity = Univercity.new(univ_params)
		if @univercity.save
			redirect_to action: :index
		else
			render 'new'
		end
	end

	def update
		@univercity = Univercity.find(params[:id])
		if @univercity.update(univ_params)
			redirect_to action: :index
		else
			render 'edit'
		end
	end

	def destroy
		@univercity = Univercity.find(params[:id])
		@univercity.destroy
		redirect_to univercities_path
	end

	private

		def univ_parms
			params.require(:univercity).permit(:name,:city,:country,:state,:slug)
		end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
end

app/helpers/application_helper.rb
module ApplicationHelper

	

end

app/helpers/colleges_helper.rb
module CollegesHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/helpers/univercities_helper.rb
module UnivercitiesHelper
def get_colleges(univercity)
	college = univercity.colleges.map(&:name).uniq
end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/univercities/_form.html.erb
<%= form_for @univercity, :html => { :class => "form-horizontal univercity" } do |f| %>

    <% if @univercity.errors.any? %>
    <div id="error_expl" class="panel panel-danger">
      <div class="panel-heading">
        <h3 class="panel-title"><%= pluralize(@univercity.errors.count, "error") %> prohibited this univercity from being saved:</h3>
      </div>
      <div class="panel-body">
        <ul>
        <% @univercity.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
        </ul>
      </div>
    </div>
  <% end %>

  <div class="control-group">
    <%= f.label :name, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :name, :class => 'form-control' %>
    </div>
    <%= error_span(@univercity[:name]) %>
  </div>
  <div class="control-group">
    <%= f.label :city, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :city, :class => 'form-control' %>
    </div>
    <%= error_span(@univercity[:city]) %>
  </div>
  <div class="control-group">
    <%= f.label :state, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :state, :class => 'form-control' %>
    </div>
    <%= error_span(@univercity[:state]) %>
  </div>
  <div class="control-group">
    <%= f.label :country, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :country, :class => 'form-control' %>
    </div>
    <%= error_span(@univercity[:country]) %>
  </div>


  <%= f.submit nil, :class => 'btn btn-primary' %>
  <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
            univercities_path, :class => 'btn btn-default' %>

<% end %>

app/views/univercities/edit.html.erb
<%- model_class = Univercity -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.edit', 'Edit %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/univercities/index.html.erb
<%- model_class = Univercity -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.pluralize.titleize %></h1>
</div>
<table class="table table-striped">
  <thead>
    <tr>
      <th><%= model_class.human_attribute_name(:name) %></th>
      <th><%= model_class.human_attribute_name(:city) %></th>
      <th><%= model_class.human_attribute_name(:state) %></th>
      <th><%= model_class.human_attribute_name(:country) %></th>
      <th><%=t '.actions', :default => t("helpers.actions") %></th>
    </tr>
  </thead>
  <tbody>
    <% @univercities.each do |univercity| %>
      <tr>
        <td><%= link_to univercity.name, univercity_path(univercity) %></td>
        <td><%= univercity.city %></td>
        <td><%= univercity.state %></td>
        <td><%= univercity.country %></td>
        <td>
          <%= link_to t('.edit', :default => t("helpers.links.edit")),
                      edit_univercity_path(univercity), :class => 'btn btn-warning btn-xs' %>
          <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
                      univercity_path(univercity),
                      :method => :delete,
                      :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
                      :class => 'btn btn-xs btn-danger' %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= link_to t('.new', :default => t("helpers.links.new")),
            new_univercity_path,
            :class => 'btn btn-primary' %>

app/views/univercities/new.html.erb
<%- model_class = Univercity -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.new', 'New %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/univercities/show.html.erb
<%- model_class = Univercity -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.titleize %></h1>
</div>

<dl class="dl-horizontal">
  <dt><strong><%= model_class.human_attribute_name(:name) %>:</strong></dt>
  <dd><%= @univercity.name %></dd>
  <dt><strong><%= model_class.human_attribute_name(:city) %>:</strong></dt>
  <dd><%= @univercity.city %></dd>
  <dt><strong><%= model_class.human_attribute_name(:state) %>:</strong></dt>
  <dd><%= @univercity.state %></dd>
  <dt><strong><%= model_class.human_attribute_name(:country) %>:</strong></dt>
  <dd><%= @univercity.country %></dd>
</dl>
<dl class="dl-horizontal">
<dt><strong>Colleges :</strong></dt>
<dd>
  <% @univercity.colleges.each do |c|%>
    <%= link_to c.name, univercity_college_path(@univercity,c)%><br>
  <% end %>
</dd>
</dl>
<%= link_to t('.back', :default => t("helpers.links.back")),
              univercities_path, :class => 'btn btn-warning'  %>
<%= link_to t('.edit', :default => t("helpers.links.edit")),
              edit_univercity_path(@univercity), :class => 'btn btn-warning' %>
<%= link_to t('.destroy', :default => t("helpers.links.destroy")),
              univercity_path(@univercity),
              :method => 'delete',
              :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
              :class => 'btn btn-danger' %>